import Navbar from "@/components/Navbar";
import "./globals.css";


export const metadata = {
  title: "Agetha - Visual Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body cz-shortcut-listen="true"
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
